# Generated by Django 3.2 on 2021-04-19 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210418_0307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='scan',
            name='description',
            field=models.CharField(max_length=1000),
        ),
    ]
